dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_00.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_01.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_02.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_03.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_04.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_05.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_07.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_08.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_09.dtb
dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_10.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
